
    <div class="row">
        <div class="col-lg-6">
      <form class="form-signin" role="form" action="/signin">
        <h2 class="form-signin-heading">Sign in</h2>
        <input type="email" class="form-control" placeholder="Email address" required autofocus>
        <input type="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
        </div>
        <div class="col-lg-6">
      <form class="form-signin" role="form" action="/register">
        <h2 class="form-signin-heading">Register</h2>
        <input type="name" class="form-control" placeholder="Name" required autofocus>
        <input type="email" class="form-control" placeholder="Email address" required autofocus>
        <input type="password" class="form-control" placeholder="Password" required>
        <input type="confirm_password" class="form-control" placeholder="Confirm Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
      </form>
        </div>
    </div>