<div class="jumbotron">
    <?if($errors):?>
    <div class="alert alert-danger">
        <ul>
            <?foreach($errors as $error):?>
            <li><?=$error->message;?></li>
            <?endforeach;?>
        </ul>
    </div>
    <?endif;?>
    <h1>Sign in</h1>
      <form class="form-signin" role="form" action="/" method="post">
    <p>
        Don't have an account? <a href="/register">Register</a>.
    </p>
    <p>
        <input type="text" name="name" class="form-control" value="<?=$user->name;?>" placeholder="Username or Email Address" required autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
    </p>
    <p>
        <input type="submit" class="btn btn-lg btn-primary" value="Sign in">
        <a class="btn btn-lg btn-success" href="/register" role="button">Register</a>
    </p>
      </form>
</div>