<div class="jumbotron">
    <?if($errors):?>
    <div class="alert alert-danger">
        <ul>
            <?foreach($errors as $error):?>
            <li><?=$error->message;?></li>
            <?endforeach;?>
        </ul>
    </div>
    <?endif;?>
    <?if($success):?>
    <p class="lead alert-success">Your account has been <strong>verified</strong>. You may now log in</p>
    <?endif;?>
    <h1>Sign in</h1>
      <form class="form-signin" role="form" action="/" method="post">
    <p>
        Don't have an account? <a href="/register">Register</a>.
    </p>
    <div class="form-group">
        <input type="text" name="name" class="form-control input-lg" value="<?=$user->name;?>" placeholder="Username or Email Address" required autofocus>
    </div>
    <div class="form-group">
        <input type="password" name="password" class="form-control input-lg" placeholder="Password" required>
    </div>
        <p class="small">
            Forgot your password? <a href="/reset-password">Reset password</a> 
        </p>
    
    <div class="form-group">
        <input type="submit" class="btn btn-lg btn-primary" value="Sign in">
        <a class="btn btn-lg btn-success" href="/register" role="button">Register</a> 
    </div>
      </form>
</div>