<div class="jumbotron">

    <?if($errors):?>
    <div class="alert alert-danger">
        <ul>
            <?foreach($errors as $error):?>
            <li><?=$error->message;?></li>
            <?endforeach;?>
        </ul>
    </div>
    <?endif;?>
    
    <p class="lead">Hi <strong><?=$user->name;?></strong>, enter your new password below to complete the process. You will be logged in automatically...</p>
    <form class="form-settings" role="form" method="post">
    <div class="form-group">
        <input type="password" class="form-control input-lg" name="new_password[]" placeholder="New Password">
        <input type="password" class="form-control input-lg" name="new_password[]" placeholder="Confirm password">
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-lg btn-primary" value="Finish">
        <a class="btn btn-lg btn-danger" href="/" role="button">Cancel</a>
    </div>
    </form>
</div>