<div class="jumbotron">
    <?if($errors):?>
    <div class="alert alert-danger">
        <ul>
            <?foreach($errors as $error):?>
            <li><?=$error->message;?></li>
            <?endforeach;?>
        </ul>
    </div>
    <?endif;?>
    <h1>New project</h1>
    <form class="form-settings" method="post" role="form">
    <div class="form-group">
        <input type="text" class="form-control input-lg" name="name" placeholder="Project name">
    </div>
    <div class="form-group">
        <label>Type user names in below to invite some collaborators</label>
        <input type="text" name="members" class="form-control tokeninput" placeholder="Search for users">
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-lg btn-primary" value="Create">
        <a class="btn btn-lg btn-danger" href="<?=http::last();?>" role="button">Cancel</a>
    </div>
    </form>
</div>
