<?if($errors):?>
<div class="alert alert-danger">
    <ul>
        <?foreach($errors as $error):?>
        <li><?=$error->message;?></li>
        <?endforeach;?>
    </ul>
</div>
<?endif;?>
<?if($tasks):?>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Due by</th>
                <th>Assigned to</th>
                <th>Started on</th>
                <?if(auth::check("edit_task")):?>
                <th>Tools</th>
                <?endif;?>
            </tr>
            </thead>
            <tbody>
                <?foreach($tasks as $task):?>
                <tr<?if($task->is_late):?> class="danger"<?elseif($task->is_due_soon):?> class="warning"<?endif;?>>
                    <td><a href="/project/<?=$project->id;?>/task/<?=$task->id;?>"><?=$task->name;?></a></td>
                    <td><?=$task->end_pretty;?></td>
                    <td>
                        <?if($task->assigned_to()) foreach($task->assigned_to() as $i => $user):?>
                        <small><a href="" class="btn btn-default btn-xs"><?=$user->name;?></a></small> 
                        <?endforeach;?>
                    </td>
                    <td><?=$task->start_pretty;?></td>
                    <?if(auth::check("edit_task")):?>
                    <td>
                        <a class="btn btn-default btn-xs align-right" href="/project/<?=$project->id;?>/edit-task/<?=$task->id;?>">Edit</a>
                        <a class="btn btn-default btn-xs align-right" href="/project/<?=$project->id;?>/task-complete/<?=$task->id;?>">Mark as complete</a>
                    </td>
                    <?endif;?>
                </tr>
                <?endforeach;?>
            </tbody>
        </table>
    </div>
<?else:?>
    <p>No tasks currently assigned to you.</p>
<?endif;?>