<?if($errors):?>
<div class="alert alert-danger">
    <ul>
        <?foreach($errors as $error):?>
        <li><?=$error->message;?></li>
        <?endforeach;?>
    </ul>
</div>
<?endif;?>
<h2><?=$vars->user()->email;?></h2>
<form role="form" method="post" action="<?=router::URL("/$project->id/modify-member/{$vars->user()->id}", "project");?>">
    <div class="form-group">
        <input type="hidden" name="email" value="<?=$vars->user()->email;?>">
    </div>
    <div class="form-group">
        <label>Permissions</label>
        <?if($permissions) foreach($permissions as $permission):?>
        <div class="checkbox">
            <label>
                <input type="hidden" name="permissions[<?=$permission->id;?>]" value="<?=($permission->id == 1)?1:0;?>">
                <input name="permissions[<?=$permission->id;?>]" value="1" type="checkbox" <?if($permission->id == 1):?>disabled="true" checked="true"<?elseif(in_array($permission->id, $user_permissions)):?> checked="true"<?endif;?>> <?=$permission->name;?>
            </label>
        </div>
        <?endforeach;?>
    </div>
    <input type="submit" class="btn btn-lg btn-primary" value="Update">
    <a class="btn btn-lg btn-primary" href="<?=router::URL("/{$project->id}/members", "project");?>" role="button">Cancel</a>
    <?if(auth::check(auth::EDIT)):?>
    <a class="btn btn-lg btn-primary" href="<?=router::URL("/{$project->id}/remove-member/{$vars->user()->id}", "project");?>" role="button" onclick="javascript:return confirm('Are you sure you want to remove <?=$vars->user()->email;?>?');">Remove Member</a>
    <?endif;?>
</form>