        <?if($members):?>
        <p>Here's a list of the project's current members.</p>
        <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Email</th>
                  <th>Permissions</th>
                </tr>
              </thead>
              <tbody>
                <?foreach($members as $user):?>
                <tr>
                    <td>
                        <?if(auth::check("modify_member")):?>
                        <a href="<?=router::URL("/{$project->id}/modify-member/{$user->id}", "project");?>"><?=$user->email;?></a>
                        <?else:?>
                        <?=$user->email;?>
                        <?endif;?>
                    </td>
                    <td>
                        <?if($user->permissions()) foreach($user->permissions() as $count => $permission):?><?=($count)?', ':'';?><?=$permission->name;?><?endforeach;?>
                    </td>
                </tr>
                <?endforeach;?>
              </tbody>
            </table>
          </div>
        <?else:?>
        <p>This project has no members.</p>
        <?endif;?>
        <p>
            <?if(auth::check("add_member")):?>
            <a class="btn btn-lg btn-primary" href="<?=router::URL('/'.$project->id.'/add-member', "project");?>" role="button">Add a member »</a>
            <?endif;?>
        </p>