<div class="jumbotron">
    <?if($errors):?>
    <div class="alert alert-danger">
        <ul>
            <?foreach($errors as $error):?>
            <li><?=$error->message;?></li>
            <?endforeach;?>
        </ul>
    </div>
    <?endif;?>
    <h1>Register</h1>
      <form class="form-signin" role="form" action="/register" method="post">
    <p>
        Username
        <input type="text" name="name" class="form-control" placeholder="Username" value="<?=$user->name;?>" required autofocus>
    </p>
    <p>
        Email address
        <input type="email" name="email" class="form-control" placeholder="Email address" value="<?=$user->email;?>" required>
    </p>
    <p>
        Password
        <input type="password" name="password[]" class="form-control" placeholder="Password" required>
        <input type="password" name="password[]" class="form-control" placeholder="Confirm Password" required>
    </p>
    <p>
        <input type="submit" class="btn btn-lg btn-primary" value="Register">
        <a class="btn btn-lg btn-danger" href="/" role="button">Cancel</a>
    </p>
      </form>
</div>