<div class="jumbotron">
    <?if($errors):?>
    <div class="alert alert-danger">
        <ul>
            <?foreach($errors as $error):?>
            <li><?=$error->message;?></li>
            <?endforeach;?>
        </ul>
    </div>
    <?endif;?>
    <p class="lead">If you forgot your password then we'll attempt to email you instructions on how to reset it. If you don't receive the email then try looking in your spam folder or allowing all emails from <strong>BPMS</strong></p>
    <form class="form-signin" role="form" method="post">
    <div class="form-group">
        <input type="text" name="name" class="form-control input-lg" value="<?=$post->name;?>" placeholder="Username or Email Address" required autofocus>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-lg btn-primary" value="Continue">
        <a class="btn btn-lg btn-danger" href="<?=http::last();?>" role="button">Cancel</a>
    </div>
    </form>
</div>