
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="/web/img/logo.png" alt="BPMS"></a>
        </div>
        <?if($user):?>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
            <li<?if($vars->action == "new-project"):?> class="active"<?endif;?>><a href="/new-project">New project</a></li>
            <li<?if($vars->action == "settings"):?> class="active"<?endif;?>><a href="/settings">Settings</a></li>
            <li class="<?if($vars->action == "projects" || $route->template == "dashboard"):?>active <?endif;?>dropdown">
                <a href="/projects" class="dropdown-toggle" data-toggle="dropdown">Projects <b class="caret"></b></a>
                <?if($global->projects):?>
                <ul class="dropdown-menu">
                    <?foreach($global->projects as $project):?>
                    <li><a href="/project/<?=$project->id;?>"><?=$project->name;?></a></li>
                    <?endforeach;?>
                    <li class="divider"></li>
                    <li><a href="/projects">All projects</a></li>
                </ul>
                <?endif;?>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text"><small>Logged in as <em><?=$user->alias;?></em></small></li>
            <li><a href="/logout">Logout</a></li>
          </ul>
          <?if($user):?><p class="navbar-text"><small></small></p><?endif;?>
        </div>
        <?endif;?>
      </div>
    </div>