
<div class="navbar navbar-default">
    <ul class="nav navbar-nav">
        <li class="<?if($route->controller == "project"):?>active <?endif;?>dropdown">
            <a href="/project/<?=$global->project->id;?>">Overview</a>
        </li>
        <li class="<?if($route->controller=="tasks" || $route->controller=="task_log"):?>active <?endif;?>dropdown">
            <a href="/project/<?=$global->project->id;?>/tasks" class="dropdown-toggle" data-toggle="dropdown">Tasks <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="/project/<?=$global->project->id;?>/tasks">My tasks</a></li>
                <li><a href="/project/<?=$global->project->id;?>/tasks/finished">Finished tasks</a></li>
                <?if(auth::has(auth::EDIT)):?>
                <li class="divider"></li>
                <li><a href="/project/<?=$global->project->id;?>/tasks/all">All tasks</a></li>
                <li><a href="/project/<?=$global->project->id;?>/tasks/create">Create task</a></li>
                <?endif;?>
            </ul>
        </li>
        <li class="<?if($route->controller == "members"):?>active <?endif;?>dropdown">
            <a href="/project/<?=$global->project->id;?>" class="dropdown-toggle" data-toggle="dropdown">Members <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="<?=router::URL("/*id/members");?>">Members</a></li>
                <?if(auth::has(auth::GRANT)):?>
                <li><a href="<?=router::URL("/*id/members/invitees");?>">Invites</a></li>
                <li class="divider"></li>
                <li><a href="<?=router::URL("/*id/members/add");?>">Invite a member</a></li>
                <li><a href="<?=router::URL("/*id/members/stats");?>">Statistics</a></li>
                <?endif;?>
            </ul>
        </li>
        <li class="<?if($route->controller == "milestone"):?>active <?endif;?>dropdown">
            <a href="<?=router::URL("/*id/milestone");?>" class="dropdown-toggle" data-toggle="dropdown">Milestones <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="<?=router::URL("/*id/milestone");?>">List</a></li>
                <?if(auth::has(auth::EDIT)):?>
                <li class="divider"></li>
                <li><a href="<?=router::URL("/*id/milestone/add");?>">Add a milestone</a></li>
                <?endif;?>
            </ul>
        </li>
    </ul>
</div>
