
<div class="navbar navbar-default">
    <ul class="nav navbar-nav">
        <li class="<?if($route->controller == "project"):?>active <?endif;?>dropdown">
            <a href="/project/<?=$global->project->id;?>">Overview</a>
        </li>
        <li class="<?if($route->controller=="tasks" || $route->controller=="task_log"):?>active <?endif;?>dropdown">
            <a href="/project/<?=$global->project->id;?>/tasks" class="dropdown-toggle" data-toggle="dropdown">Tasks <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="/project/<?=$global->project->id;?>/tasks">My tasks</a></li>
                <li><a href="/project/<?=$global->project->id;?>/tasks/finished">Finished tasks</a></li>
                <?if(auth::has(auth::EDIT)):?>
                <li class="divider"></li>
                <li><a href="/project/<?=$global->project->id;?>/tasks/all">All tasks</a></li>
                <li><a href="/project/<?=$global->project->id;?>/tasks/create">Create task</a></li>
                <?endif;?>
            </ul>
        </li>
        <li class="<?if($route->controller == "members"):?>active <?endif;?>dropdown">
            <a href="/project/<?=$global->project->id;?>" class="dropdown-toggle" data-toggle="dropdown">Members <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="<?=router::URL("/*id/members");?>">List</a></li>
                <?if(auth::has(auth::GRANT)):?>
                <li class="divider"></li>
                <li><a href="<?=router::URL("/*id/members/add");?>">Add a member</a></li>
                <?endif;?>
            </ul>
        </li>
        <?/*if(auth::check("add_milestone")):?>
        <li<?if($vars->action=="add-milestone"):?> class="active"<?endif;?>><a href="/project/<?=$global->project->id;?>/add-milestone">Add a milestone</a></li>
        <?endif;*/?>
    </ul>
</div>