<?if($errors):?>
<div class="alert alert-danger">
    <ul>
        <?foreach($errors as $error):?>
        <li><?=$error->message;?></li>
        <?endforeach;?>
    </ul>
</div>
<?endif;?>
<form role="form" method="post" action="<?=router::URL("/*id/members/add");?>">
    <div class="form-group">
        <label for="user_name">Username</label>
        <input type="text" name="name" class="form-control" value="<?=$data->name;?>" id="user_name" placeholder="Username">
    </div>
    <div class="form-group">
        <label>Permissions</label>
        <?if($permissions) foreach($permissions as $permission):?>
        <div class="checkbox">
            <label>
                <input type="hidden" name="permissions[<?=$permission->id;?>]" value="<?=($permission->id == 1)?1:0;?>">
                <input name="permissions[<?=$permission->id;?>]" value="1" type="checkbox" <?if($permission->id == 1):?>disabled="true" checked="true"<?endif;?>> <?=$permission->name;?>
            </label>
        </div>
        <?endforeach;?>
    </div>
    <input type="submit" class="btn btn-lg btn-primary" value="Add">
    <a class="btn btn-lg btn-primary" href="<?=router::URL("/*id/members");?>" role="button">Cancel</a>
</form>