        <?if($members):?>
        <p>Here's a list of the project's current members.</p>
        <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Alias</th>
                  <th>Permissions</th>
                  <?if(auth::check("modify_member")):?>
                  <th class="align-right">Tools</th>
                  <?endif;?>
                </tr>
              </thead>
              <tbody>
                <?foreach($members as $user):?>
                <tr<?if($project->creator_id == $user->id):?> class="active"<?endif;?>>
                    <td>
                        <?if(auth::check("modify_member")):?>
                            <a href="<?=router::URL("/*id/members/view/{$user->id}");?>"><?=$user->alias;?></a>
                            <?if($project->creator_id == $user->id):?><small>creator</small><?endif;?>
                        <?else:?>
                            <?=$user->alias;?>
                        <?endif;?>
                    </td>
                    <td>
                        <?foreach($permissions as $count => $permission):?>
                        <span title="<?=$permission->name;?>" class="glyphicon glyphicon-<?=$permission->icon;?><?if(!$user->has_permission($permission->id)):?> glyphicon-disabled<?endif;?>"></span>
                        <?endforeach;?>
                    </td>
                    <?if(auth::check("modify_member")):?>
                    <td class="align-right">
                    <div class="btn-group">
                        <a href="<?=router::URL("/*id/members/modify/{$user->id}");?>" class="btn btn-xs btn-default<?if($project->creator_id == $user->id):?> disabled<?endif;?>"><span class="glyphicon glyphicon-pencil"></span></a>
                        <?if(auth::check("remove_member")):?>
                        <a href="<?=router::URL("/*id/members/remove/{$user->id}");?>" class="btn btn-xs btn-default<?if($project->creator_id == $user->id):?> disabled<?endif;?>" onclick="javascript:return confirm('Are you sure you want to remove <?=$user->alias;?>?');"><span class="glyphicon glyphicon-trash"></span></a>
                        <?endif;?>
                    </div>
                    </td>
                    <?endif;?>
                </tr>
                <?endforeach;?>
              </tbody>
            </table>
          </div>
        <?else:?>
        <p>This project has no members.</p>
        <?endif;?>
        <p>
            <?if(auth::check("add_member")):?>
            <a class="btn btn-lg btn-primary" href="<?=router::URL('/*id/members/add');?>" role="button">Add a member »</a>
            <?endif;?>
        </p>
