        <?if($members):?>
        <p>Here's a list of the project's current members.</p>
        <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Alias</th>
                  <?if(auth::check("modify_member")):?>
                  <th>Tools</th>
                  <th>Permissions</th>
                  <?endif;?>
                </tr>
              </thead>
              <tbody>
                <?foreach($members as $user):?>
                <tr<?if($project->creator_id == $user->id):?> class="active"<?endif;?>>
                    <td>
                        <?if($project->creator_id == $user->id):?>
                        <strong><?=$user->alias;?></strong> <small>creator</small>
                        <?else:?>
                            <?if(auth::check("modify_member")):?>
                            <a href="<?=router::URL("/*id/members/modify/{$user->id}");?>"><?=$user->alias;?></a>
                            <?else:?>
                            <?=$user->alias;?>
                            <?endif;?>
                        <?endif;?>
                    </td>
                    <?if(auth::check("modify_member")):?>
                    <td>
                        <a href="<?=router::URL("/*id/members/modify/{$user->id}");?>" class="btn btn-xs btn-default">Edit</a>
                        <?if(auth::check("remove_member")):?>
                        <a href="<?=router::URL("/*id/members/remove/{$user->id}");?>" class="btn btn-xs btn-default" onclick="javascript:return confirm('Are you sure you want to remove <?=$user->alias;?>?');">Remove</a>
                        <?endif;?>
                    </td>
                    <td>
                        <?if($user->permissions()) foreach($user->permissions() as $count => $permission):?>
                        <a href="#" class="btn btn-xs btn-warning disabled"><?=$permission->name;?></a>
                        <?endforeach;?>
                    </td>
                    <?endif;?>
                </tr>
                <?endforeach;?>
              </tbody>
            </table>
          </div>
        <?else:?>
        <p>This project has no members.</p>
        <?endif;?>
        <p>
            <?if(auth::check("add_member")):?>
            <a class="btn btn-lg btn-primary" href="<?=router::URL('/*id/members/add');?>" role="button">Add a member »</a>
            <?endif;?>
        </p>
