<?if($errors):?>
<div class="alert alert-danger">
    <ul>
        <?foreach($errors as $error):?>
        <li><?=$error->message;?></li>
        <?endforeach;?>
    </ul>
</div>
<?endif;?>
<h2><?=$vars->user()->alias;?></h2>
<form role="form" method="post" action="<?=router::URL("/*id/members/modify/{$vars->user()->id}");?>">
    <div class="form-group">
        <input type="hidden" name="name" value="<?=$vars->user()->name;?>">
    </div>
    <div class="form-group">
        <label>Permissions</label>
        <?if($permissions) foreach($permissions as $permission):?>
        <div class="checkbox">
            <label>
                <span class="glyphicon glyphicon-<?=$permission->icon;?>"></span>
                <input type="hidden" name="permissions[<?=$permission->id;?>]" value="<?=($permission->id == 1)?1:0;?>">
                <input name="permissions[<?=$permission->id;?>]" value="1" type="checkbox"<?if($permission->id == 1):?> disabled="true"<?endif;?><?if(in_array($permission->id, $user_permissions)):?> checked="true"<?endif;?>> <?=$permission->name;?>
            </label>
        </div>
        <?endforeach;?>
    </div>
    <input type="submit" class="btn btn-lg btn-primary" value="Update">
    <?if(auth::check("remove_member")):?>
    <a class="btn btn-lg btn-danger" href="<?=router::URL("/*id/members/remove/{$vars->user()->id}");?>" role="button" onclick="javascript:return confirm('Are you sure you want to remove <?=$vars->user()->alias;?>?');">Remove Member</a>
    <?endif;?>
    <a class="btn btn-lg btn-default" href="<?=router::URL("/*id/members");?>" role="button">Cancel</a>
</form>