<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Verify email &middot; BPMS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body style="margin: 0; padding: 0;">
<h1>Verify your email</h1>
<h3>Someone has just registered your email (<?=$email;?>) with BPMS</h3>
<p>If it was you, activate your account: <a href="http://bpms.danoitek.com/verify/<?=$hash;?>"><?=$hash;?></a></p>

<p><?=$message;?></p>

</body>

</html>