<?if($errors):?>
<div class="alert alert-danger">
    <ul>
        <?foreach($errors as $error):?>
        <li><?=$error->message;?></li>
        <?endforeach;?>
    </ul>
</div>
<?endif;?>
<form role="form" method="post">
<div class="form-group">
    <label for="task_name">Name</label>
    <input name="name" type="text" class="form-control" id="task_name" placeholder="Name" value="<?=$milestone->name;?>">
</div>
<?/*<div class="form-group">
    <label for="task_start_date">Starts</label>
    <div class="form-inline">
        <input class="form-control" type="date" name="start_date" id="task_start_date" value="<?=$milestone->start_date?$milestone->start_date:$default->start_date;?>">
        <input class="form-control" type="time" name="start_time" id="task_start_time" value="<?=$milestone->start_time?$milestone->start_time:$default->start_time;?>">
    </div>
</div>*/?>
<div class="form-group">
    <label for="task_start_date">Ends</label>
    <div class="form-inline">
        <input class="form-control" type="date" name="end_date" id="task_start_date" value="<?=$milestone->end_date?$milestone->end_date:$default->end_date;?>">
        <input class="form-control" type="time" name="end_time" id="task_start_time" value="<?=$milestone->end_time?$milestone->end_time:$default->end_time;?>">
    </div>
</div>
<div class="form-group">
    <label for="task_description">Description</label>
    <textarea name="description" id="task_description" class="form-control" placeholder="Description" rows="5"><?=$milestone->description;?></textarea>
</div>
    <input type="submit" class="btn btn-lg btn-primary" value="<?=$submit_name;?>">
    <a class="btn btn-lg btn-danger" href="<?=http::last();?>" role="button">Cancel</a>
</form>
