<?if($errors):?>
<div class="alert alert-danger">
    <ul>
        <?foreach($errors as $error):?>
        <li><?=$error->message;?></li>
        <?endforeach;?>
    </ul>
</div>
<?endif;?>
<?if($milestones):?>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Ends</th>
                <th class="align-right">Tools</th>
            </tr>
            </thead>
            <tbody>
                <?foreach($milestones as $milestone):?>
                <tr>
                    <td><a href="<?=router::URL("/*id/milestone/modify/$milestone->id");?>"><?=$milestone->name;?></a></td>
                    <td><?=$milestone->end_pretty;?></td>
                    <td class="align-right">
                    <div class="btn-group">
                        <a class="btn btn-xs btn-default<?if(!auth::has(auth::EDIT)):?> disabled<?endif;?>" href="<?=router::URL("/*id/milestone/modify/$milestone->id");?>" title="Modify milestone"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-xs btn-default<?if(!auth::has(auth::DELETE)):?> disabled<?endif;?>" href="<?=router::URL("/*id/milestone/remove/$milestone->id");?>" title="Remove milestone"><span class="glyphicon glyphicon-trash"></span></a>
                    </div>
                    </td>
                </tr>
                <?endforeach;?>
            </tbody>
        </table>
    </div>
<?else:?>
    <p><?=$message;?></p>
<?endif;?>
