<?if($errors):?>
<div class="alert alert-danger">
    <ul>
        <?foreach($errors as $error):?>
        <li><?=$error->message;?></li>
        <?endforeach;?>
    </ul>
</div>
<?endif;?>
<?if($task):?>
<div class="col-sm-8">
    
    <blockquote><?=$task->description;?></blockquote>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Log</h3>
        </div>
        <div class="panel-body">
            <?if($log):?>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Who</th>
                        <th>When</th>
                        <th>Total</th>
                        <th>Note</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?foreach($log as $entry):?>
                    <tr>
                        <td>
                            <?if($entry->user()->id == auth::user()->id):?>
                            <a class="btn btn-default btn-xs" href="<?=router::URL("/*id/tasks/log/$task->id/edit/$entry->id");?>"><span class="glyphicon glyphicon-pencil"></span></a>
                            <?endif;?> 
                            <?=$entry->user()->alias;?>
                        </td>
                        <td><?=$entry->pretty_date;?></td>
                        <td>
                            <?if($entry->hours):?><?=$entry->hours;?><small>h</small> <?endif;?> 
                            <?=$entry->minutes;?><small>m</small>
                        </td>
                        <td><?=$entry->note;?></td>
                    </tr>
                    <?endforeach;?>
                    </tbody>
                </table>
            </div>
            <?else:?>
            <p>No time logged yet</p>
            <?endif;?>
        </div>
    </div>
</div>
<div class="col-sm-4">

    <div class="btn-group btn-group-margin">
        <?if($task->assigned_to_me()):?>
        <a class="btn btn-default btn-md" href="<?=router::URL("/*id/tasks/log/$task->id/add");?>" title="Log time"><span class="glyphicon glyphicon-time"></span> Log time</a>
        <?endif;?>
        <?if(auth::check("edit")):?>
        <a class="btn btn-default btn-md" href="<?=router::URL("/*id/tasks/edit/$task->id");?>" title="Edit"><span class="glyphicon glyphicon-pencil"></span></a>
        <?if(!$task->complete):?>
        <a class="btn btn-default btn-md" href="<?=router::URL("/*id/tasks/task-complete/$task->id");?>" title="Mark as complete"><span class="glyphicon glyphicon-ok"></span></a>
        <?else:?>
        <a class="btn btn-default btn-md" href="<?=router::URL("/*id/tasks/task-incomplete/$task->id");?>" title="Re-open task"><span class="glyphicon glyphicon-folder-open"></span></a>
        <?endif;?>
        <?if(auth::check("remove")):?>
        <a class="btn btn-danger btn-md" href="<?=router::URL("/*id/tasks/remove/$task->id");?>" title="Remove" onclick="javascript:return confirm('Are you sure you want to remove &quot;<?=$task->name;?>&quot;?');"><span class="glyphicon glyphicon-trash"></span></a>
        <?endif;?>
        <?endif;?>
    </div>
    <?if($task->complete):?>
    <blockquote class="alert-success">Finished</blockquote>
    <?else:?>
    <blockquote class="<?if($task->is_late):?>alert-danger<?elseif($task->is_due_soon):?>alert-warning<?else:?>alert-info<?endif;?>">Due <?=$task->end_pretty;?></blockquote>
    <blockquote class="alert-info">Started <?=$task->start_pretty;?></blockquote>
    <?endif;?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Collaborators</h3>
        </div>
        <?if($task->assigned_to()):?>
        <div class="panel-body">
            <?foreach($task->assigned_to() as $i => $user):?>
            <a href="<?=router::URL("/*id/members/view/{$user->id}");?>" class="btn btn-med <?if(auth::user()->id == $user->id):?>btn-primary<?else:?>btn-default<?endif;?>"><?=$user->name;?></a>
            <?endforeach;?>
        </div>
        <?endif;?>
    </div>

</div>
<?else:?>
<p>Task not found.</p>
<?endif;?>
