<?if($errors):?>
<div class="alert alert-danger">
    <ul>
        <?foreach($errors as $error):?>
        <li><?=$error->message;?></li>
        <?endforeach;?>
    </ul>
</div>
<?endif;?>
<form role="form" method="post">
    <div class="form-group">
        <label for="task_name">Name</label>
        <input name="name" type="email" class="form-control" id="task_name" placeholder="Name">
    </div>
    <div class="form-group">
        <label for="task_description">Description</label>
        <textarea name="description" id="task_description" class="form-control" placeholder="Description" rows="3"></textarea>
    </div>
    <input type="submit" class="btn btn-lg btn-primary" value="Create">
    <a class="btn btn-lg btn-primary" href="<?=router::URL("/$project->id", "project");?>" role="button">Cancel</a>
</form>