
<style type="text/css">
.bpms-overview{
    width: 100%;
    font-size: 1em;
    overflow: hidden;
    border: 1px solid #ccc;
}
.bpms-overview-content{
    margin-bottom: -1px;
}
.bpms-overview-shim{
    width: 1000em;
}

.bpms-overview-content,
.bpms-ov-month,
.bpms-ov-day,
.bpms-ov-cell{
    float: left;
}

.bpms-ov-row{
    width: 10000px;
}
.bpms-ov-cell{
    text-align: center;
    width: 100%;
    margin-bottom: -1px;
    border-bottom: 1px solid #ccc;
}
.bpms-ov-cell .bpms-ov-content{
    display: block;
    height: 2em;
    border-right: 1px solid #ccc;
    line-height: 2em;
}
.bpms-clear{
    clear: both;
}
.bpms-ov-month{
    width: 62em;
}
.bpms-ov-day{
    width: 2em;
}
</style>

<div class="bpms-overview">

<div class="bpms-overview-content"><div class="bpms-overview-shim">

<div class="bpms-ov-month">
    <div class="bpms-ov-cell">
        <div class="bpms-ov-content">January</div>
    </div>
    <?for($i = 1; $i <= 31; $i++):?>
    <div class="bpms-ov-day">
        <div class="bpms-ov-cell">
            <div class="bpms-ov-content"><?=$i;?></div>
        </div>
    </div>
    <?endfor;?>
    <?for($i = 1; $i <= 31; $i++):?>
    <div class="bpms-ov-day">
        <div class="bpms-ov-cell">
            <div class="bpms-ov-content"><?$day = date('D', strtotime("1/$i/2014")); echo $day[0];?></div>
        </div>
    </div>
    <?endfor;?>
    <?for($r = 1; $r <= 10; $r++):?>
    <?for($i = 1; $i <= 31; $i++):?>
    <div class="bpms-ov-day">
        <div class="bpms-ov-cell">
            <div class="bpms-ov-content"></div>
        </div>
    </div>
    <?endfor;?>
    <?endfor;?>
</div>

<div class="bpms-ov-month">
    <div class="bpms-ov-cell">
        <div class="bpms-ov-content">February</div>
    </div>
</div>

</div></div>

<div class="bpms-clear"></div>

</div>