<?if(!$tasks):?>
<p>No tasks yet</p>
<?else:?>

<?if($milestones):?>
<div class="bpms-milestones btn-group">
    <a class="btn btn-md btn-default<?if(!$current_ms):?> active<?endif;?>" href="<?=router::URL("/*id/index/all");?>">All</a>
    <?foreach($milestones as $milestone):?>
    <a class="btn btn-md btn-default<?if($current_ms->id == $milestone->id):?> active<?endif;?>" href="<?=router::URL("/*id/index/$milestone->id");?>"><?=$milestone->name;?></a>
    <?endforeach;?>
</div>
<?endif;?>
<?/*if($milestones):?>
<ul class="bpms-milestones nav nav-tabs">
    <li<?if(!$current_ms):?> class="active"<?endif;?>><a href="<?=router::URL("/*id/index/all");?>">All</a>
    <?foreach($milestones as $milestone):?>
    <li<?if($current_ms->id == $milestone->id):?> class="active"<?endif;?>><a href="<?=router::URL("/*id/index/$milestone->id");?>"><?=$milestone->name;?></a>
    <?endforeach;?>
</ul>
<?endif;*/?>

<div id="bpms-overview" class="bpms-overview">
<?$start = ($current_ms && $current_ms->last()) ? $current_ms->last()->end : $bounds->start;?>
<?$offset = ($current_ms && $current_ms->end < time()) ? $current_ms->end : time();?>
<div class="bpms-overview-content" id="<?=round(($offset - strtotime(date('m/1/Y', $start)))/86400);?>">
<?$end = $current_ms ? $current_ms->end : $bounds->end;?>
<?if(date('n', $start)==date('n', $end))$end = strtotime("+1 month", $start);?>
<?$diff = $end - $start;?>
<?$length = ceil((int)($diff / 86400));?>
<?$width = 0;?>
<?$end_buffer = strtotime(date('m/1/Y', strtotime("+1 month", $end)));?>
<?$timestamp = $start;?>
<div class="bpms-ov-header">
<?while($timestamp <= $end_buffer):?>
<?$year=(int)date('Y', $timestamp);?>
<?$m=(int)date('n', $timestamp);?>
<?$days_in_mo=(int)date('t', strtotime("$m/1/$year"));?>
<div class="bpms-ov-month bpms-ov-month<?=$days_in_mo;?>">
    <div class="bpms-ov-cell">
        <div class="bpms-ov-content<?if("$m/1/$year" == date('n/1/Y')):?> bpms-ov-active<?endif;?>"><?=$day = date('F', strtotime("$m/1/$year"));?><?if((int)date('Y', strtotime("$m/1/$year")) != date('Y', time())):?> <?=date('Y', strtotime("$m/1/$year"));?><?endif;?></div>
    </div>
    <?for($i = 1; $i <= $days_in_mo; $i++):?>
    <div class="bpms-ov-day bpms-ov-dayh">
        <div class="bpms-ov-cell">
            <div class="bpms-ov-content<?if("$m/$i/$year" == date('n/j/Y')):?> bpms-ov-active<?endif;?>"><?=$i;?></div>
        </div>
    </div>
    <?endfor;?>
    <?for($i = 1; $i <= $days_in_mo; $i++):?>
    <?$width+=2;?>
    <div class="bpms-ov-day bpms-ov-dayh">
        <div class="bpms-ov-cell">
            <div class="bpms-ov-content<?if("$m/$i/$year" == date('n/j/Y')):?> bpms-ov-active<?endif;?>"><?$day = date('D', strtotime("$m/$i/$year")); echo $day[0];?></div>
        </div>
    </div>
    <?endfor;?>
</div>
<?$timestamp = strtotime("+1 month", $timestamp);?>
<?endwhile;?>
</div>


<?$timestamp = $start;?>
<?while($timestamp <= $end_buffer):?>
<?$year=(int)date('Y', $timestamp);?>
<?$m=(int)date('n', $timestamp);?>
<?$days_in_mo=(int)date('t', strtotime("$m/1/$year"));?>
<div class="bpms-ov-month bpms-ov-month<?=$days_in_mo;?>">
    <?foreach($tasks as $index => $task):?>
    <?$used = array();?>
    <?for($i = 1; $i <= $days_in_mo; $i++):?>
    <div class="bpms-ov-day">
        <div class="bpms-ov-cell">
            <div class="bpms-ov-content<?if("$m/$i/$year" == date('n/j/Y')):?> bpms-ov-active<?endif;?>">
                <?if(strtotime(date("n/j/Y", $task->start)) == strtotime("$m/$i/$year")):?>
                <div class="bpms-ov-entry">
                    <div class="bpms-ov-eshim" style="left:<?=round(($task->start-strtotime("$m/$i/$year"))/86400,1)*2;?>em;width:<?=round(($task->end-$task->start)/86400, 1)*2;?>em;">
                    <div class="progress progress-striped">
                        <a title="<?=preg_replace('#\s#', '&nbsp;', $task->name);?>" data-toggle="tooltip" data-placement="top" href="<?=router::URL("/*id/tasks/view/$task->id");?>" class="bpms-tooltip progress-bar<?if($task->complete):?> progress-bar-success<?elseif($task->is_late):?> progress-bar-danger<?elseif($task->is_due_soon):?> progress-bar-warning<?else:?> progress-bar-info<?endif;?>" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                            <span class="sr-only"><?=$task->name;?></span>
                        </a>
                    </div>
                    </div>
                </div>
                <?endif;?>
            </div>
        </div>
    </div>
    <?endfor;?>
    <?endforeach;?>
    
</div>
<?$timestamp = strtotime("+1 month", $timestamp);?>
<?endwhile;?>

<style type="text/css">
.bpms-overview-content{
    width: <?=$width;?>em;
}
</style>

</div>

<div class="bpms-clear"></div>

</div>
<?endif;?>
