<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/web/ico/favicon.ico">

    <title><?if($global->title):?><?=$global->title;?> &middot; <?endif;?>BPMS</title>

    <!-- Bootstrap core CSS -->
    <link href="/web/css/bootstrap.min.css" rel="stylesheet">
    <link href="/web/css/multi-select.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/web/css/default.css" rel="stylesheet">
    <link href="/web/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="/web/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <?=view()->nav->main(array('user'=>$user,"vars"=>$vars,"route"=>$route,"global"=>$global));?>
    <div class="container dashboard">
        <h1><?=$global->project->name;?></h1>
        <?=view()->nav->project(array('user'=>$user,"vars"=>$vars,"route"=>$route,"global"=>$global));?>
        <div class="bpms-panel">
                <?/*<?if($global->breadcrumb):?>
                <ol class="breadcrumb">
                    <?foreach($global->breadcrumb as $name => $action):?>
                        <?if($action == $route->action):?>
                        <li><?=$name;?></li>
                        <?else:?>
                        <li><a href="<?=router::URL("/".$global->project->id.($action?"/$action":''));?>"><?=$name;?></a></li>
                        <?endif;?>
                    <?endforeach;?>
                </ol>
                <?endif;?>*/?>
            <div class="bpms-panel-body">
                <h3 class="page-header"><?=$global->title;?></h3>
                <?=$content;?>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/web/js/bootstrap.min.js"></script>
    <script src="/web/js/jquery.multi-select.js"></script>
    <script src="/web/js/dashboard.js"></script>
    <script src="/web/js/docs.min.js"></script>
    <script src="/web/js/typeahead.js"></script>
    <script src="/web/js/default.js"></script>
  </body>
</html>
