<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>BPMS Alert</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body style="margin: 0; padding: 0;">

<h1><?=$alert->project_name;?></h1>

<h3><a href="bpms.danoitek.com/project/<?=$alert->project_id;?>/tasks/view/<?=$alert->task_id;?>"><?=$alert->task_name;?></a></h3>

<p>Hey <?=$alert->user_name;?>, <?=$message;?></p>

<p>&copy; BPMS</p>

</body>

</html>